# Generated by Django 5.2.7 on 2025-10-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Prova')),
                ('data_prova', models.DateField(verbose_name='Data da Prova')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('link_anexos', models.URLField(blank=True, null=True, verbose_name='Link para Anexos (Drive/Lista)')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='agenda.materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name_plural': 'Provas',
                'ordering': ['data_prova'],
            },
        ),
    ]
