# Generated by Django 5.2.7 on 2025-10-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_prova'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LINK', 'Link Externo'), ('PDF', 'Arquivo PDF'), ('TXT', 'Texto/Anotação'), ('OUTRO', 'Outro Arquivo')], default='LINK', max_length=5, verbose_name='Tipo de Material')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Recurso')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais_provas/', verbose_name='Anexo de Arquivo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Material')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='agenda.prova', verbose_name='Prova Relacionada')),
            ],
            options={
                'verbose_name_plural': 'Materiais de Apoio',
            },
        ),
    ]
