# Generated by Django 5.2.7 on 2025-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_materialdeapoio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='data_prova',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Prova'),
        ),
    ]
