# Generated by Django 5.2.7 on 2025-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_prova_data_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='notas_materia',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações da Matéria'),
        ),
    ]
