# Generated by Django 5.2.7 on 2025-11-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_materia_notas_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='media_final',
            field=models.FloatField(blank=True, null=True, verbose_name='Média Final'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nota1',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota Prova 1'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nota2',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota Prova 2'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nota_trabalho',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota Trabalho'),
        ),
    ]
