# Generated by Django 5.2.7 on 2025-11-04 01:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_materia_media_final_materia_nota1_materia_nota2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nota_trabalho',
        ),
        migrations.CreateModel(
            name='AtividadeAvaliativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Atividade (Ex: P1, Trabalho)')),
                ('peso_percentual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso (%)')),
                ('nota_obtida', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota (0 a 10)')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='agenda.materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name_plural': 'Atividades Avaliativas',
                'unique_together': {('materia', 'nome')},
            },
        ),
    ]
