# Generated by Django 5.2.7 on 2025-11-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_materia_nota1_remove_materia_nota2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='media_final',
        ),
        migrations.DeleteModel(
            name='AtividadeAvaliativa',
        ),
    ]
