# Generated by Django 5.2.7 on 2025-11-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_horarioaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioaula',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
