# Generated by Django 5.2.7 on 2025-11-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_horarioaula_hora_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioaula',
            name='hora_fim',
        ),
    ]
