# Generated by Django 5.2.7 on 2025-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_remove_horarioaula_hora_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='link_anexo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Anexo/Material de Apoio'),
        ),
    ]
