# Generated by Django 5.2.7 on 2025-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_tarefa_link_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='link_plano_ensino',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Plano de Ensino'),
        ),
    ]
